class Constant
  BOOKING_COUNTRY_TITLE = "%s酒店预订-酒店"
  BOOKING_COUNTRY_DESCRIPTION = "%s热门酒店预订"
  BOOKING_COUNTRY_KEYWORDS = "%s"
  BOOKING_CITY_TITLE = "%s酒店预订-酒店"
  BOOKING_CITY_DESCRIPTION = "%s热门酒店预订"
  BOOKING_CITY_KEYWORDS = "%s"
  BOOKING_DETAIL_TITLE = "%s酒店预订-酒店"
  BOOKING_DETAIL_DESCRIPTION = "%s热门酒店预订"
  BOOKING_DETAIL_KEYWORDS = "%s"
  LANG_CN_CC = ['cn','hk','tw','sg']
end
